name: clothesstore
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  intl: ^0.17.0
  provider: ^6.0.1
  share_plus: ^4.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/
